# Generated by Django 2.1.7 on 2019-04-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='公司名称')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=50, verbose_name='工作经验')),
                ('salary', models.FloatField(verbose_name='薪资')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '工作信息',
                'verbose_name_plural': '工作信息',
            },
        ),
        migrations.CreateModel(
            name='OfficeArea',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='工作区域')),
            ],
            options={
                'verbose_name': '工作区域',
                'verbose_name_plural': '工作区域',
            },
        ),
        migrations.CreateModel(
            name='OfficeSkills',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='技能要求')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='工作类型')),
            ],
            options={
                'verbose_name': '工作类型',
                'verbose_name_plural': '工作类型',
            },
        ),
        migrations.AddField(
            model_name='office',
            name='officeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.OfficeType', verbose_name='工作类型'),
        ),
        migrations.AddField(
            model_name='office',
            name='skills',
            field=models.ManyToManyField(to='office.OfficeSkills', verbose_name='技能要求'),
        ),
        migrations.AddField(
            model_name='company',
            name='officeArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.OfficeArea', verbose_name='工作区域'),
        ),
    ]
