# Generated by Django 2.1.7 on 2019-04-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='houseID',
            field=models.IntegerField(default=0, max_length=50, primary_key=True, serialize=False, verbose_name='房子id'),
        ),
    ]
