# Generated by Django 2.1.7 on 2019-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinfo',
            name='meters',
            field=models.IntegerField(verbose_name='平米数'),
        ),
    ]
