# Generated by Django 2.1.7 on 2019-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_hisprice_housead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='img_link',
            field=models.CharField(default=0, max_length=255, verbose_name='图片链接'),
        ),
    ]
