# Generated by Django 2.1.7 on 2019-04-06 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190405_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hisprice',
            fields=[
                ('houseID', models.IntegerField(primary_key=True, serialize=False, verbose_name='房子id')),
                ('totalPrice', models.FloatField(verbose_name='总价')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellinfo',
            name='community',
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': '小区', 'verbose_name_plural': '小区'},
        ),
        migrations.AlterModelOptions(
            name='houseinfo',
            options={'verbose_name': '在售房源信息', 'verbose_name_plural': '在售房源信息'},
        ),
        migrations.AlterModelOptions(
            name='rentinfo',
            options={'verbose_name': '租房信息', 'verbose_name_plural': '租房信息'},
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='houseState',
            field=models.CharField(default='在售', max_length=50, verbose_name='房源状态'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='updatedate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='成交时间'),
        ),
        migrations.AlterField(
            model_name='community',
            name='validdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Community', verbose_name='小区名称'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='followInfo',
            field=models.CharField(max_length=50, verbose_name='关注数'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='房子id'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='square',
            field=models.FloatField(max_length=50, verbose_name='房屋面积'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='validdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='houseID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='房子id'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='meters',
            field=models.FloatField(verbose_name='平米数'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='price',
            field=models.FloatField(max_length=50, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='updatedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Sellinfo',
        ),
    ]
