# Generated by Django 2.1.7 on 2019-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190424_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='动态标题')),
                ('url', models.CharField(max_length=255, verbose_name='动态链接')),
                ('source', models.CharField(max_length=50, verbose_name='动态来源')),
                ('date_time', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='动态发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='Web_sign_new',
            fields=[
                ('Date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='日期')),
                ('House_num', models.IntegerField(verbose_name='网上签约数量')),
                ('House_square', models.IntegerField(verbose_name='网上签约面积')),
                ('Online_num', models.IntegerField(verbose_name='住宅签约数量')),
                ('Online_square', models.IntegerField(verbose_name='住宅签约面积')),
            ],
        ),
        migrations.CreateModel(
            name='Web_sign_old',
            fields=[
                ('Date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='日期')),
                ('Online_num', models.IntegerField(verbose_name='住宅签约数量')),
            ],
        ),
        migrations.AlterModelOptions(
            name='houseinfo',
            options={'verbose_name': '房源信息', 'verbose_name_plural': '房源信息'},
        ),
        migrations.RemoveField(
            model_name='rentinfo',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='rentinfo',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='rentinfo',
            name='other',
        ),
        migrations.RemoveField(
            model_name='rentinfo',
            name='updatedate',
        ),
        migrations.RemoveField(
            model_name='rentinfo',
            name='zone',
        ),
        migrations.AddField(
            model_name='rentinfo',
            name='direction',
            field=models.CharField(default=0, max_length=50, verbose_name='房屋朝向'),
        ),
        migrations.AddField(
            model_name='rentinfo',
            name='floor',
            field=models.CharField(default=0, max_length=50, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='rentinfo',
            name='lable',
            field=models.CharField(default=0, max_length=50, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='rentinfo',
            name='rent_time',
            field=models.CharField(default=0, max_length=50, verbose_name='租期'),
        ),
        migrations.AddField(
            model_name='rentinfo',
            name='shelf_time',
            field=models.DateTimeField(default=0, verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='hisprice',
            name='houseAD',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='link',
            field=models.CharField(max_length=255, verbose_name='房子链接'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='region',
            field=models.CharField(default=0, max_length=50, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='subway',
            field=models.CharField(default=0, max_length=255, verbose_name='地铁站'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='房子名称'),
        ),
    ]
