# Generated by Django 2.1.7 on 2019-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190424_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='动态标题')),
                ('url', models.CharField(max_length=255, verbose_name='动态链接')),
                ('source', models.CharField(max_length=50, verbose_name='动态来源')),
                ('date_time', models.CharField(max_length=100, verbose_name='动态发布时间')),
            ],
        ),
    ]
