# Generated by Django 2.1.7 on 2019-04-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190424_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseinfo',
            options={'verbose_name': '房源信息', 'verbose_name_plural': '房源信息'},
        ),
    ]
