# Generated by Django 2.1.7 on 2019-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190407_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hisprice',
            name='houseID',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='房子id'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseID',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='房子id'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='houseID',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='房子id'),
        ),
    ]
