# Generated by Django 2.1.7 on 2019-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20190407_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='link',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='链接地址'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='link',
            field=models.CharField(default=0, max_length=255, verbose_name='房子链接'),
        ),
        migrations.AlterField(
            model_name='rentinfo',
            name='link',
            field=models.CharField(default=0, max_length=255, verbose_name='房子链接'),
        ),
    ]
